### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by AndrewRocky** [BreadFish64/AndroidUsbAudioDevice#1]
1. In readme.md - [https://zadig.akeo.ie/.Zadig](https://zadig.akeo.ie/.Zadig) (porbably should change to https://zadig.akeo.ie)
2. In android_usb_audio_source.cpp - [https://breadfish64.github.io](https://breadfish64.github.io)

**Comment by BreadFish64** [comment]
Ah, I just noticed these issues. I think I already fixed the Zadig one. My website doesn't have a home page, I just put the URL in there as a placeholder.
