### ISSUE TITLE
problem if android device has usb debugging enabled

### ISSUE THREAD

**Issue by AndrewRocky** [BreadFish64/AndroidUsbAudioDevice#5]
AudioSource can't find android device if it has usb debugging enabled.
It gets stuck on "Attempting to connect to device, n tries left" loops

I don't know if it's fixable, but it probably should be mentioned in the readme before drivers manipulation

**Comment by BreadFish64** [comment]
I don't think there's anything I can do about it. I relied on logging mostly for debugging.
Google's documentation suggests that certain devices can be in debug and accessory mode simultaneously but it sounds like it was only a couple Nexus models. Even my old Google Pixel didn't work.
